spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/loanDb
    driver-class-name: org.mariadb.jdbc.Driver
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true