spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./src/main/resources/database/loandb;AUTO_SERVER=TRUE
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: update