### 無/有寬限期，單一利率
POST http://localhost:8080/loan/calculate
Content-Type: application/json

{
  "loanAmount": 200,
  "loanPeriod": 36,
  "isSingleRate": true,
  "interestRate": 2,
  "gracePeriod": 3
}

### 無/有寬限期，多段式利率
POST http://localhost:8080/loan/calculate
Content-Type: application/json

{
  "loanAmount": 100,
  "loanPeriod": 36,
  "isSingleRate": false,
  "ratePeriods": [
    {"rate": 2,"months": 12},
    {"rate": 3, "months": 24}
  ],
  "gracePeriod": 0
}

### 新增APR，單一利率
POST http://localhost:8080/loan/calculate
Content-Type: application/json

{
  "loanAmount": 100,
  "loanPeriod": 36,
  "isSingleRate": true,
  "interestRate": 2,
  "gracePeriod": 3,
  "relatedFees": 0
}

### 新增APR，多段式利率
POST http://localhost:8080/loan/calculate
Content-Type: application/json

{
  "loanAmount": 100,
  "loanPeriod": 36,
  "isSingleRate": false,
  "ratePeriods": [
    {"rate": 2,"months": 12},
    {"rate": 3, "months": 24}
  ],
  "gracePeriod": 10,
  "relatedFees": 100000
}